name = "Fortnight"
author = "Austin Hudson"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40fcc7bcc0ae0ac42eaae220c070395ae160bdc790a03e23a0d38010540ae8eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
