name = "Fortnight"
author = "Austin Hudson"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08ac3b2f86a6db0973887d3dd5e26eb2ca8fd0470ead7c3b8385db89caddc4b0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
