name = "Fortnight"
author = "Austin Hudson"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96ecf0ebccc47ee00e41cbe6b330a033eb85c396fe0a0e838307278ff077097c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
